### ISSUE TITLE
viewController being retained but not released

### ISSUE THREAD

**Issue by mikemonaco** [SurveyMonkey/surveymonkey-ios-sdk#46]
the viewController passed into presentFromViewController, or scheduleInterceptFromViewController seems to be retained by the SurveyMonkey SDK but never released. This is stoping the view controller which presents the survey from being dealloced when the time comes and can lead to many different types of bugs and memory leaks

**Comment by benleiken** [comment]
@mikemonaco this issue should be fixed in the version i just released (2.0.2)! let me know if it still crops up.

**Comment by mikemonaco** [comment]
@benleiken seems to still happen in latest version (2.0.3), demo project attached shows the issue in action. If you run the app and tap "Click Me", and then tap "< Back" you will see that ViewController gets dealloced (via NSLog in ViewController.m). But if you tap "Show Survey" before clicking "< Back" you will see that ViewController does not get dealloced.

[survey_monkey_test.zip](https://github.com/SurveyMonkey/surveymonkey-ios-sdk/files/2177990/survey_monkey_test.zip)
